### ISSUE TITLE
Undefined variable calls

### ISSUE THREAD

**Issue by repositony** [GEOUNED-code/GEOUNED#14]
Found a few calls to undefined variables looking through the code for this.

For GEOUNED
- translate.py: `opt.verbose` in `setDefinition`
- CellDefinition.py: presumably `self.elements` under `getSurfValue` should be `Definition.elements`
- \_\_init\_\_.py: under `Start()` I'm not sure what `res` is supposed to be here
  - `print("unexpected constant cell {} :{}".format(c.__id__, res))`

For GEOReverse
- MCNPInput.py: `get_ellipsoid_parameters()` does not know what `axis` is, should it be `iaxis`?
-  Objects.py has a lot 
  - `parts` in `getSubCell()`
  - `onesht` in `transform()` of `HyperbolicCylinder`, `EllipticCylinder`, and `Ellipsoid`
  - `r` in `transform()` for `Paraboloid`
  - `length` in `makeEllipsoid()`
- remh.py: `cell_card_string.__card_split__` does not know what `m1` is
- splitFunction.py: `surface_side()` has a couple of mis-spellings of radii as `raddii`

**Comment by repositony** [comment]
Also `BasicFunctions_part2.py` should import `isInLine` and `isInPlane` from part1 since they are used in the file

**Comment by psauvan** [comment]
Undefined variables have been fixed.
Thank you for your contributions.
