### ISSUE TITLE
[Feature request] -conda forge package

### ISSUE THREAD

**Issue by shimwell** [GEOUNED-code/GEOUNED#177]
# Is your feature request related to a problem? Please describe.
Currently we use conda forge to bring in freecad then pip install to bring in geouned package. If we make a conda forage package then we can make these two install instructions into a single install command.

# Describe the solution you'd like
a conda forge distribution of geouned

# Describe alternatives you've considered
an improved pip install that compiles freecad

# Additional context
I shall make a PR to conda forge stage recipes with the required meta.yml.
It would be great to add a few others as maintainers, please comment on the [conda forge PR](https://github.com/conda-forge/staged-recipes/pull/26385) and volunteer if you are happy to be added as a maintainer for the conda forge recipe.

**Comment by alberto743** [comment]
Regarding the alternative you have considered, I guess that compiling FreeCAD should not be part of our business. In general, I rather employ pip packages and not conda, but I understand that with conda you may profit of the already available FreeCAD package.

**Comment by alberto743** [comment]
Apparently also FreeCAD upstream support conda-style installation for their software: https://wiki.freecad.org/Conda.
