### ISSUE TITLE
missing header in step file

### ISSUE THREAD

**Issue by church89** [GEOUNED-code/GEOUNED#3]
Hi, 
I tried to follow you example in the readme section and after running `GEO.SetOptions()`, I get the following error: `configparser.MissingSectionHeaderError: File contains no section headers`. 
I tried with several step files and all gave me the same problem. Am I missing something?

**Comment by psauvan** [comment]
Hi Lorenzo,

You have to call the GEOUNED class with the name of the file in which the options to run GEOUNED are defined. The method setOptions will initialize GEOUNED with these options.
This error message makes me think that your configuration file is not properly defined.
An example of configuration file can be found in the "scripts" folder.
You can find also in this folder a script that run automatically GEOUNED.
