### ISSUE TITLE
value error: math domain error in boolean solids check sign during void generation

### ISSUE THREAD

**Issue by py1sl** [GEOUNED-code/GEOUNED#39]
during void generation I recieved a value error: math domain error
this was caused by the check_sign function in booleansolids.py

specifically  around line 531 the 'alpha = math.acos(z)'  where z must be between -1 and 1 otherwise it generates the math domain error.
in this case the preceding r.normalize gave the following vector 
Vector (0.8433914458128906, 0.5372996083468161, 9.709052043679794e-14)
and the z value was 
-1.0000000000000002
 
It looks like a tolerance/ numerical precision issue as a temporary fix I have added a rounding function

**Comment by psauvan** [comment]
fixed! thanks
