### ISSUE TITLE
incorrect cell definition - not using all added surfaces 

### ISSUE THREAD

**Issue by py1sl** [GEOUNED-code/GEOUNED#42]
When converting from stp to mcnp the attached file does not correctly convert.  
It is very like the example in the GEOUNED paper figures 5-7. 
It has a spherical surface which requires extra planes to be added to stop the cell going to infinity but they are not added to the cell definition.
surfaces 1 and 3 are added by GEOUNED but are not used in any cell definition.  
Adding surface  +1 to cell 1 definition will prevent the cell going to infinity.

[c1.zip](https://github.com/GEOUNED-code/GEOUNED/files/14909885/c1.zip)

**Comment by psauvan** [comment]
It seems you are using an old version of GEOUNED. New version add extra the plane.
